import {
  type Courier,
  type CourierLeaderboardEntry,
  type Customer,
  type PerformanceSummary,
  type RoleCredentials,
  type Shipment,
  type TrendPoint,
} from "./types";

const BASE_TIME = new Date("2025-03-03T09:30:00Z");

const minutesAgo = (minutes: number) =>
  new Date(BASE_TIME.getTime() - minutes * 60 * 1000).toISOString();

const minutesFromNow = (minutes: number) =>
  new Date(BASE_TIME.getTime() + minutes * 60 * 1000).toISOString();

export const ROLE_CREDENTIALS: RoleCredentials[] = [
  {
    username: "admin",
    password: "admin",
    role: "admin",
    displayName: "Avery Miles",
  },
  {
    username: "courier",
    password: "courier",
    role: "courier",
    displayName: "Jordan Reed",
    contextId: "courier-001",
  },
  {
    username: "customer",
    password: "customer",
    role: "customer",
    displayName: "Priya Patel",
    contextId: "cust-001",
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    name: "Priya Patel",
    email: "priya.patel@example.com",
    phone: "+1 (312) 555-0147",
    address: "45 Market Street",
    city: "Chicago",
    region: "Central",
    notes: "Prefers evening deliveries after 6 PM.",
  },
  {
    id: "cust-002",
    name: "Liam Chen",
    email: "liam.chen@example.com",
    phone: "+1 (415) 555-2099",
    address: "88 Mission Blvd",
    city: "San Francisco",
    region: "West",
  },
  {
    id: "cust-003",
    name: "Sara Ibrahim",
    email: "sara.ibrahim@example.com",
    phone: "+1 (646) 555-3310",
    address: "77 Hudson Yard",
    city: "New York",
    region: "East",
    notes: "Office tower requires dock access code.",
  },
  {
    id: "cust-004",
    name: "Miguel Torres",
    email: "miguel.torres@example.com",
    phone: "+1 (786) 555-7832",
    address: "19 Biscayne Ave",
    city: "Miami",
    region: "South",
  },
];

export const COURIERS: Courier[] = [
  {
    id: "courier-001",
    name: "Jordan Reed",
    avatar: "",
    phone: "+1 (312) 555-8801",
    vehicle: "E-Van • Ford Transit",
    region: "Central",
    status: "online",
    lastSeen: minutesAgo(2),
    location: { lat: 41.887, lng: -87.635 },
    speedKmh: 42,
    assignments: ["ship-001", "ship-006"],
    metrics: {
      onTimeRate: 0.96,
      deliveriesToday: 18,
      distanceTodayKm: 122,
      averageEtaVarianceMinutes: -4,
      rating: 4.9,
    },
  },
  {
    id: "courier-002",
    name: "Amelia Brooks",
    avatar: "",
    phone: "+1 (415) 555-4410",
    vehicle: "Cargo Bike • Urban Arrow XL",
    region: "West",
    status: "online",
    lastSeen: minutesAgo(5),
    location: { lat: 37.79, lng: -122.4 },
    speedKmh: 21,
    assignments: ["ship-002"],
    metrics: {
      onTimeRate: 0.99,
      deliveriesToday: 12,
      distanceTodayKm: 48,
      averageEtaVarianceMinutes: 2,
      rating: 4.8,
    },
  },
  {
    id: "courier-003",
    name: "Diego Martínez",
    avatar: "",
    phone: "+1 (646) 555-8822",
    vehicle: "Compact Van • Nissan NV200",
    region: "East",
    status: "break",
    lastSeen: minutesAgo(9),
    location: { lat: 40.75, lng: -73.995 },
    speedKmh: 0,
    assignments: ["ship-003", "ship-004", "ship-008"],
    metrics: {
      onTimeRate: 0.91,
      deliveriesToday: 16,
      distanceTodayKm: 98,
      averageEtaVarianceMinutes: 8,
      rating: 4.6,
    },
  },
  {
    id: "courier-004",
    name: "Fatima Al-Hassan",
    avatar: "",
    phone: "+1 (786) 555-6621",
    vehicle: "Scooter • NIU NQi Sport",
    region: "South",
    status: "online",
    lastSeen: minutesAgo(1),
    location: { lat: 25.775, lng: -80.2 },
    speedKmh: 34,
    assignments: ["ship-005", "ship-007"],
    metrics: {
      onTimeRate: 0.94,
      deliveriesToday: 14,
      distanceTodayKm: 76,
      averageEtaVarianceMinutes: -2,
      rating: 4.7,
    },
  },
];

export const SHIPMENTS: Shipment[] = [
  {
    id: "ship-001",
    trackingId: "TRK-641823",
    orderNumber: "ORD-8745",
    customerId: "cust-001",
    courierId: "courier-001",
    status: "in_transit",
    createdAt: minutesAgo(360),
    pickupScheduledAt: minutesAgo(300),
    pickedUpAt: minutesAgo(290),
    deliveredAt: undefined,
    etaMinutes: 35,
    lastUpdated: minutesAgo(4),
    weightKg: 3.2,
    serviceLevel: "same_day",
    region: "Central",
    origin: "Fulfillment Hub • West Loop",
    destination: "45 Market Street, Chicago",
    timeline: [
      { status: "Label Created", timestamp: minutesAgo(340) },
      { status: "Picked Up", timestamp: minutesAgo(290) },
      {
        status: "Departed Facility",
        timestamp: minutesAgo(150),
        note: "Loaded with downtown route",
      },
      {
        status: "In Transit",
        timestamp: minutesAgo(45),
        note: "Courier 3.1 km from destination",
      },
    ],
    route: [
      { lat: 41.8841, lng: -87.6396, label: "Hub" },
      { lat: 41.8881, lng: -87.633, label: "Stop" },
      { lat: 41.8905, lng: -87.6293, label: "Current" },
      { lat: 41.8898, lng: -87.6217, label: "Destination" },
    ],
  },
  {
    id: "ship-002",
    trackingId: "TRK-428190",
    orderNumber: "ORD-5190",
    customerId: "cust-002",
    courierId: "courier-002",
    status: "delivered",
    createdAt: minutesAgo(540),
    pickupScheduledAt: minutesAgo(480),
    pickedUpAt: minutesAgo(475),
    deliveredAt: minutesAgo(20),
    etaMinutes: 0,
    lastUpdated: minutesAgo(20),
    weightKg: 1.1,
    serviceLevel: "same_day",
    region: "West",
    origin: "Micro Hub • SoMa",
    destination: "88 Mission Blvd, San Francisco",
    timeline: [
      { status: "Picked Up", timestamp: minutesAgo(475) },
      { status: "In Transit", timestamp: minutesAgo(90) },
      { status: "Delivered", timestamp: minutesAgo(20), note: "Left with reception" },
    ],
    route: [
      { lat: 37.7792, lng: -122.3971, label: "Hub" },
      { lat: 37.7878, lng: -122.399, label: "Stop" },
      { lat: 37.7908, lng: -122.3997, label: "Delivered" },
    ],
  },
  {
    id: "ship-003",
    trackingId: "TRK-917632",
    orderNumber: "ORD-6540",
    customerId: "cust-003",
    courierId: "courier-003",
    status: "delayed",
    createdAt: minutesAgo(780),
    pickupScheduledAt: minutesAgo(600),
    pickedUpAt: minutesAgo(590),
    deliveredAt: undefined,
    etaMinutes: 90,
    lastUpdated: minutesAgo(12),
    weightKg: 5.4,
    serviceLevel: "next_day",
    region: "East",
    origin: "Regional Depot • Newark",
    destination: "77 Hudson Yard, New York",
    timeline: [
      { status: "Picked Up", timestamp: minutesAgo(590) },
      {
        status: "Delay Reported",
        timestamp: minutesAgo(130),
        note: "Traffic incident on Lincoln Tunnel",
      },
      {
        status: "Rerouted",
        timestamp: minutesAgo(75),
        note: "Using FDR alternative route",
      },
    ],
    route: [
      { lat: 40.7357, lng: -74.1724, label: "Depot" },
      { lat: 40.758, lng: -73.995, label: "Delay" },
      { lat: 40.754, lng: -73.984, label: "Current" },
      { lat: 40.7549, lng: -73.9816, label: "Destination" },
    ],
  },
  {
    id: "ship-004",
    trackingId: "TRK-812673",
    orderNumber: "ORD-1024",
    customerId: "cust-003",
    courierId: "courier-003",
    status: "pending",
    createdAt: minutesAgo(90),
    pickupScheduledAt: minutesFromNow(30),
    etaMinutes: 210,
    lastUpdated: minutesAgo(8),
    weightKg: 2.4,
    serviceLevel: "standard",
    region: "East",
    origin: "Fulfillment Center • Queens",
    destination: "77 Hudson Yard, New York",
    timeline: [
      { status: "Scheduled", timestamp: minutesAgo(85) },
      { status: "Awaiting Pickup", timestamp: minutesAgo(10) },
    ],
    route: [
      { lat: 40.6782, lng: -73.9442, label: "Planned" },
      { lat: 40.7128, lng: -74.006, label: "Destination" },
    ],
  },
  {
    id: "ship-005",
    trackingId: "TRK-238761",
    orderNumber: "ORD-8842",
    customerId: "cust-004",
    courierId: "courier-004",
    status: "in_transit",
    createdAt: minutesAgo(420),
    pickupScheduledAt: minutesAgo(360),
    pickedUpAt: minutesAgo(355),
    etaMinutes: 25,
    lastUpdated: minutesAgo(3),
    weightKg: 0.9,
    serviceLevel: "same_day",
    region: "South",
    origin: "Warehouse • Coral Gables",
    destination: "19 Biscayne Ave, Miami",
    timeline: [
      { status: "Picked Up", timestamp: minutesAgo(355) },
      { status: "In Transit", timestamp: minutesAgo(50) },
      {
        status: "Out for Delivery",
        timestamp: minutesAgo(25),
        note: "Courier on last mile segment",
      },
    ],
    route: [
      { lat: 25.748, lng: -80.268, label: "Hub" },
      { lat: 25.761, lng: -80.219, label: "Current" },
      { lat: 25.775, lng: -80.19, label: "Destination" },
    ],
  },
  {
    id: "ship-006",
    trackingId: "TRK-554712",
    orderNumber: "ORD-9961",
    customerId: "cust-001",
    courierId: "courier-001",
    status: "delivered",
    createdAt: minutesAgo(920),
    pickupScheduledAt: minutesAgo(840),
    pickedUpAt: minutesAgo(830),
    deliveredAt: minutesAgo(210),
    etaMinutes: 0,
    lastUpdated: minutesAgo(210),
    weightKg: 6.2,
    serviceLevel: "standard",
    region: "Central",
    origin: "Regional Hub • Joliet",
    destination: "45 Market Street, Chicago",
    timeline: [
      { status: "Picked Up", timestamp: minutesAgo(830) },
      { status: "In Transit", timestamp: minutesAgo(480) },
      {
        status: "Delivered",
        timestamp: minutesAgo(210),
        note: "Signed by recipient",
      },
    ],
    route: [
      { lat: 41.525, lng: -88.083, label: "Origin" },
      { lat: 41.7, lng: -87.8, label: "Route" },
      { lat: 41.889, lng: -87.63, label: "Delivered" },
    ],
  },
  {
    id: "ship-007",
    trackingId: "TRK-663782",
    orderNumber: "ORD-1144",
    customerId: "cust-004",
    courierId: "courier-004",
    status: "pending",
    createdAt: minutesAgo(65),
    pickupScheduledAt: minutesFromNow(10),
    etaMinutes: 140,
    lastUpdated: minutesAgo(6),
    weightKg: 4.1,
    serviceLevel: "standard",
    region: "South",
    origin: "Warehouse • Doral",
    destination: "19 Biscayne Ave, Miami",
    timeline: [
      { status: "Scheduled", timestamp: minutesAgo(60) },
      { status: "Assigning Courier", timestamp: minutesAgo(10) },
    ],
    route: [
      { lat: 25.818, lng: -80.355, label: "Origin" },
      { lat: 25.775, lng: -80.19, label: "Destination" },
    ],
  },
  {
    id: "ship-008",
    trackingId: "TRK-227341",
    orderNumber: "ORD-7052",
    customerId: "cust-003",
    courierId: "courier-003",
    status: "in_transit",
    createdAt: minutesAgo(520),
    pickupScheduledAt: minutesAgo(450),
    pickedUpAt: minutesAgo(445),
    etaMinutes: 55,
    lastUpdated: minutesAgo(9),
    weightKg: 2.7,
    serviceLevel: "next_day",
    region: "East",
    origin: "Cross-dock • Brooklyn",
    destination: "77 Hudson Yard, New York",
    timeline: [
      { status: "Picked Up", timestamp: minutesAgo(445) },
      {
        status: "Arrived at Facility",
        timestamp: minutesAgo(220),
        note: "Scanned at Midtown micro hub",
      },
      {
        status: "In Transit",
        timestamp: minutesAgo(40),
        note: "Courier 5 stops away",
      },
    ],
    route: [
      { lat: 40.678, lng: -73.944, label: "Origin" },
      { lat: 40.706, lng: -73.99, label: "Hub" },
      { lat: 40.748, lng: -73.99, label: "Current" },
      { lat: 40.7549, lng: -73.9816, label: "Destination" },
    ],
  },
];

export const PERFORMANCE_SUMMARY: PerformanceSummary[] = [
  {
    period: "today",
    deliveries: 97,
    onTimeRate: 0.942,
    delayed: 6,
    averageEtaVarianceMinutes: -3,
    kmTravelled: 812,
    carbonEstimateKg: 74,
  },
  {
    period: "week",
    deliveries: 612,
    onTimeRate: 0.927,
    delayed: 44,
    averageEtaVarianceMinutes: 2,
    kmTravelled: 4895,
    carbonEstimateKg: 443,
  },
  {
    period: "month",
    deliveries: 2470,
    onTimeRate: 0.938,
    delayed: 162,
    averageEtaVarianceMinutes: 1,
    kmTravelled: 19420,
    carbonEstimateKg: 1730,
  },
];

export const DELIVERY_TRENDS: TrendPoint[] = [
  { label: "Mon", delivered: 82, delayed: 6, inTransit: 14 },
  { label: "Tue", delivered: 91, delayed: 5, inTransit: 20 },
  { label: "Wed", delivered: 95, delayed: 7, inTransit: 18 },
  { label: "Thu", delivered: 104, delayed: 4, inTransit: 15 },
  { label: "Fri", delivered: 112, delayed: 9, inTransit: 23 },
  { label: "Sat", delivered: 86, delayed: 6, inTransit: 12 },
  { label: "Sun", delivered: 73, delayed: 4, inTransit: 9 },
];

export const COURIER_LEADERBOARD: CourierLeaderboardEntry[] = [
  {
    courierId: "courier-002",
    name: "Amelia Brooks",
    avatar: "",
    deliveries: 142,
    onTimeRate: 0.985,
    satisfaction: 4.9,
  },
  {
    courierId: "courier-001",
    name: "Jordan Reed",
    avatar: "",
    deliveries: 168,
    onTimeRate: 0.964,
    satisfaction: 4.92,
  },
  {
    courierId: "courier-004",
    name: "Fatima Al-Hassan",
    avatar: "",
    deliveries: 131,
    onTimeRate: 0.954,
    satisfaction: 4.88,
  },
  {
    courierId: "courier-003",
    name: "Diego Martínez",
    avatar: "",
    deliveries: 154,
    onTimeRate: 0.918,
    satisfaction: 4.63,
  },
];

export const REGION_PERFORMANCE = [
  {
    region: "Central",
    deliveries: 215,
    successRate: 0.951,
    averageEtaVarianceMinutes: -4,
  },
  {
    region: "West",
    deliveries: 184,
    successRate: 0.972,
    averageEtaVarianceMinutes: 1,
  },
  {
    region: "East",
    deliveries: 196,
    successRate: 0.908,
    averageEtaVarianceMinutes: 7,
  },
  {
    region: "South",
    deliveries: 171,
    successRate: 0.943,
    averageEtaVarianceMinutes: -1,
  },
];

export const RECENT_EVENTS = [
  {
    id: "event-001",
    timestamp: minutesAgo(12),
    type: "status",
    title: "Delay resolved",
    description: "Shipment TRK-917632 rerouted and back on schedule.",
  },
  {
    id: "event-002",
    timestamp: minutesAgo(28),
    type: "handoff",
    title: "Courier swap completed",
    description: "Route East-4 reassigned from Diego Martínez to express partner.",
  },
  {
    id: "event-003",
    timestamp: minutesAgo(51),
    type: "alert",
    title: "Temperature spike avoided",
    description: "Cold-chain parcel TRK-641823 stabilized after hub alert.",
  },
] satisfies Array<{
  id: string;
  timestamp: string;
  title: string;
  description: string;
  type: "status" | "handoff" | "alert";
}>;
